FROM mcr.microsoft.com/azurelinux/base/core:3.0

RUN tdnf -y install --setopt=install_weak_deps=False \
    btrfs-progs \
    dhcpcd \
    nbd \
    qemu

RUN tdnf -y install \
    asciidoc \
    bash-completion \
    bluez \
    cargo \
    chrony \
    cifs-utils \
    cryptsetup \
    device-mapper-multipath \
    e2fsprogs \
    fuse3 \
    gcc \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jq \
    kbd \
    kexec-tools \
    kernel \
    kmod-devel \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    make \
    mdadm \
    ndctl \
    nfs-utils \
    nvme-cli \
    parted \
    pcsc-lite \
    qemu-kvm \
    rng-tools \
    rsyslog \
    squashfs-tools \
    swtpm \
    systemd-boot \
    systemd-resolved \
    systemd-ukify \
    tpm2-tools \
    xfsprogs \
    xorriso \
    && tdnf -y update && tdnf clean all
